#!/bin/sh

scriptdir=$(dirname "$0")

if [ "x$1" == "x" ]; then
	echo Error no input file
	exit 1
fi

fullfile=$1
filename=$(basename "$fullfile")
extension="${filename##*.}"
filename="${filename%%.*}"

tmpfilebase=/tmp/shl_$filename

$scriptdir/build/shlc $fullfile -o $tmpfilebase.ll
# $scriptdir/build/shlc -O3 $fullfile -o $tmpfilebase.ll
# $scriptdir/build/shlc -O0 -g $fullfile -o $tmpfilebase.ll
llc $tmpfilebase.ll
gcc $tmpfilebase.s -L$scriptdir/build -lstdshl -o $filename
rm $tmpfilebase.s
rm $tmpfilebase.ll
